apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    alicloud-pvname: uat-archery-keys-pv
  name: uat-archery-keys-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: /UAT-K8S-TOPLIST/uat-archery-dms/keys
      server: 03427932-krsg.cn-shanghai.extreme.nas.aliyuncs.com
      vers: '3'
    volumeHandle: uat-archery-keys-pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem
