apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uat-archery-goinception
  name: uat-archery-goinception
  namespace: uat-archery
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uat-archery-goinception
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uat-archery-goinception
    spec:
      containers:
        - image: >-
            toplist-registry-vpc.cn-shanghai.cr.aliyuncs.com/88/tl-archery-dms:goinception-v1.3.0
          imagePullPolicy: Always
          name: uat-archery-goinception
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config.toml
              name: volume-1665379346270
              subPath: config.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: uat-archery-goinception
          name: volume-1665379346270
